services:
  - type: web
    name: oj-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    dockerCommand: sh -c "dockerd & sleep 10 && npm start"
    privileged: true 